import type { Metadata } from "next";
import "./globals.css";
import { EB_Garamond, Inter } from "next/font/google";
import { LayoutWrapper } from "@/components/LayoutWrapper";
import { Analytics } from "@vercel/analytics/next";

const garamond = EB_Garamond({
  subsets: ["latin"],
  variable: "--font-garamond",
});
const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${garamond.variable} ${inter.variable}`}>
        <Analytics />
        <LayoutWrapper>{children}</LayoutWrapper>
      </body>
    </html>
  );
}
